### ISSUE TITLE
tail call optimization

### ISSUE THREAD

**Issue by polluks** [adumont/cerberus2080#6]
https://github.com/adumont/cerberus2080/blob/cea57a96f91ed75d59dec1a63dd909ba1ab49e05/forth.s#L2983
https://github.com/adumont/cerberus2080/blob/cea57a96f91ed75d59dec1a63dd909ba1ab49e05/forth.s#L2195
simply use `JMP`

**Comment by adumont** [comment]
Thanks, I've learned something new ("tail call optimization"). Makes a lot of sense actually :+1: 

Fixed in 947f76f
