### ISSUE TITLE
This instruction is redundant

### ISSUE THREAD

**Issue by polluks** [adumont/cerberus2080#7]
https://github.com/adumont/cerberus2080/blob/cea57a96f91ed75d59dec1a63dd909ba1ab49e05/forth.s#L119
See https://en.wikipedia.org/wiki/WDC_65C02#Bug_fixes

**Comment by adumont** [comment]
Hum... not sure I want to remove this one. It's not a big gain and I have a feeling it's safer for beginners (like me). I may gain confidence at some point to remove it :).
